#version: '3.8'
services:
  auth_service:
    container_name: auth_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Mapea el puerto 3000 del contenedor al 3000 del host
    volumes:
      - .:/app
      - /app/node_modules # Ignora los node_modules locales
    command: npm run dev # Ejecuta el servidor en modo desarrollo
    environment:
      - NODE_ENV=development

  nginx:
    container_name: nginx-container
    image: nginx:1.25.1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "83:83"
    depends_on:
      - auth_service

  db:
    image: postgres:15.2-alpine3.17
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=0neOne$1
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
